# Generated by Django 5.0.1 on 2024-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(max_length=11)),
                ('about', models.TextField()),
                ('working_days_start', models.CharField(max_length=200)),
                ('working_days_end', models.CharField(max_length=200)),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
            ],
        ),
    ]
