# Generated by Django 5.0.1 on 2024-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
