# Generated by Django 5.0 on 2023-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_reservation_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='menu_id',
            field=models.ManyToManyField(to='cafe.menu'),
        ),
    ]
