# Generated by Django 5.0 on 2023-12-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_reservation_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='table_id',
            new_name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_time',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
