# Generated by Django 5.0 on 2023-12-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_rename_menu_id_reservation_menu_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="number",),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="tables",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tables",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tables",
            name="url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
